.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pySystemRDLModel-github| image:: https://img.shields.io/badge/pyEDAA-pySystemRDLModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel
.. |SHIELD:png:pySystemRDLModel-github| image:: https://raster.shields.io/badge/pyEDAA-pySystemRDLModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel

.. # Sourcecode license
.. |SHIELD:svg:pySystemRDLModel-src-license| image:: https://img.shields.io/pypi/l/pySystemRDLModel?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:pySystemRDLModel-src-license| image:: https://img.shields.io/pypi/l/pySystemRDLModel?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pySystemRDLModel-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/tags
.. |SHIELD:png:pySystemRDLModel-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/tags

.. # GitHub release
.. |SHIELD:svg:pySystemRDLModel-release| image:: https://img.shields.io/github/v/release/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/releases/latest
.. |SHIELD:png:pySystemRDLModel-release| image:: https://raster.shields.io/github/v/release/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/releases/latest

.. # GitHub release date
.. |SHIELD:svg:pySystemRDLModel-date| image:: https://img.shields.io/github/release-date/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/releases
.. |SHIELD:png:pySystemRDLModel-date| image:: https://raster.shields.io/github/release-date/edaa-org/pySystemRDLModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pySystemRDLModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/network/dependents
.. |SHIELD:png:pySystemRDLModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pySystemRDLModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemRDLModel/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/actions/workflows/Pipeline.yml
.. |SHIELD:png:pySystemRDLModel-gha-test| image:: https://raster.shields.io/github/workflow/status/edaa-org/pySystemRDLModel/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:pySystemRDLModel-codacy-quality| image:: https://img.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySystemRDLModel
.. |SHIELD:png:pySystemRDLModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySystemRDLModel

.. # Codacy - coverage
.. |SHIELD:svg:pySystemRDLModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySystemRDLModel
.. |SHIELD:png:pySystemRDLModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySystemRDLModel

.. # Codecov - coverage
.. |SHIELD:svg:pySystemRDLModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySystemRDLModel
.. |SHIELD:png:pySystemRDLModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pySystemRDLModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySystemRDLModel

.. # Libraries - source rank
.. |SHIELD:svg:pySystemRDLModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemRDLModel/sourcerank
.. |SHIELD:png:pySystemRDLModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemRDLModel/sourcerank

.. # PyPI tag
.. |SHIELD:svg:pySystemRDLModel-pypi-tag| image:: https://img.shields.io/pypi/v/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySystemRDLModel/
.. |SHIELD:png:pySystemRDLModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySystemRDLModel/

.. # PyPI project status
.. |SHIELD:svg:pySystemRDLModel-pypi-status| image:: https://img.shields.io/pypi/status/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pySystemRDLModel-pypi-status| image:: https://raster.shields.io/pypi/status/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pySystemRDLModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pySystemRDLModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pySystemRDLModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pySystemRDLModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemRDLModel
.. |SHIELD:png:pySystemRDLModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pySystemRDLModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemRDLModel

.. # Requires - status
.. |SHIELD:svg:pySystemRDLModel-req-status| image:: https://img.shields.io/requires/github/edaa-org/pySystemRDLModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySystemRDLModel/requirements/?branch=main
.. |SHIELD:png:pySystemRDLModel-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pySystemRDLModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySystemRDLModel/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:pySystemRDLModel-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pySystemRDLModel-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/edaa-org/pySystemRDLModel/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pySystemRDLModel-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpySystemRDLModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpySystemRDLModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySystemRDLModel/
.. |SHIELD:png:pySystemRDLModel-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpySystemRDLModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpySystemRDLModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySystemRDLModel/

.. # Gitter
.. |SHIELD:svg:pySystemRDLModel-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:pySystemRDLModel-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
